baseurl: "/weekly"
name: "Crisp Minimal Weekly"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: weekly-post
      type: post
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - LICENSE
  - README.md
  - /rake
